name: Publish lab PDFs

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  convert-markdown-to-pdf:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Pandoc
      run: sudo apt-get install -y pandoc

    - name: Install LaTeX
      run: sudo apt-get install -y texlive-xetex texlive-latex-extra texlive-fonts-recommended texlive-fonts-extra

    - name: Convert Markdown to LaTeX and compile to PDF
      run: |
        for file in labs/lab00/README.md; do
          filename=$(echo "$file" | tr / - | sed 's/README.md//')
          pandoc "$file" -s --pdf-engine=xelatex -o "${filename}.pdf"
        done

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: "auto-release-${{ github.sha }}"
        release_name: "Auto Release ${{ github.sha }}"
        draft: true  # Set this to false if you don't want a draft release
        prerelease: false

    - name: Upload PDFs to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./*.pdf
        asset_content_type: application/pdf