name: Publish lab PDFs

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  convert-markdown-to-pdf:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Pandoc
      run: sudo apt-get install -y pandoc hub

    - name: Install LaTeX
      run: sudo apt-get install -y texlive-xetex texlive-latex-extra texlive-fonts-recommended texlive-fonts-extra

    - name: Convert Markdown to LaTeX and compile to PDF
      run: |
        set -x
        for dir in 00 01; do
          cd labs/lab$dir
          pandoc README.md -f gfm -s --pdf-engine=xelatex -o "../../lab$dir.pdf" -V mainfont="DejaVu Sans" -V monofont="DejaVu Sans Mono"
          cd ../..
        done

    - name: Upload PDFs to GitHub Releases
      run: |
        set -x
        assets=()
        for asset in ./*.pdf; do
          assets+=("-a" "$asset")
        done
        tag_name="${GITHUB_REF##*/}"
        hub release create "${assets[@]}" -m "$tag_name" "$tag_name"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
